GET http://localhost:3000/tweets


###
GET http://localhost:3000/tweets/634b06f0dab67acd1ec90e1a


###
POST http://localhost:3000/tweets
Content-Type: application/json

{
  "content": "Hello World",
  "screenName": "Victor Pagnozi"
}
